const Map<String, List<String>> carBrandsAndModels = {
  'Toyota': [
    'Corolla',
    'Camry',
    'RAV4',
    'Tacoma',
    'Highlander',
    '4Runner',
    'Tundra',
    'Prius',
    'Sienna'
  ],
  'Ford': [
    'F-150',
    'Mustang',
    'Explorer',
    'Escape',
    'Bronco',
    'Edge',
    'Expedition',
    'Maverick',
    'Ranger'
  ],
  'Chevrolet': [
    'Silverado',
    'Malibu',
    'Equinox',
    'Traverse',
    'Camaro',
    'Tahoe',
    'Trailblazer',
    'Colorado',
    'Blazer'
  ],
  'Honda': [
    'Civic',
    'Accord',
    'CR-V',
    'Pilot',
    'Odyssey',
    'Ridgeline',
    'HR-V',
    'Passport'
  ],
  'Nissan': [
    'Altima',
    'Sentra',
    'Rogue',
    'Pathfinder',
    'Frontier',
    'Versa',
    'Murano',
    'Titan',
    'Armada'
  ],
  'Hyundai': [
    'Elantra',
    'Sonata',
    'Tucson',
    'Santa Fe',
    'Palisade',
    'Accent',
    'Venue',
    'Ioniq 5',
    'Kona'
  ],
  'Kia': [
    'Forte',
    'Optima',
    'Sportage',
    'Sorento',
    'Telluride',
    'Rio',
    'Soul',
    'Seltos',
    'Carnival'
  ],
  'Jeep': [
    'Wrangler',
    'Grand Cherokee',
    'Cherokee',
    'Compass',
    'Renegade',
    'Gladiator',
    'Wagoneer'
  ],
  'Subaru': [
    'Outback',
    'Forester',
    'Impreza',
    'Crosstrek',
    'Legacy',
    'Ascent',
    'BRZ'
  ],
  'Volkswagen': [
    'Jetta',
    'Passat',
    'Tiguan',
    'Atlas',
    'Golf',
    'Taos',
    'ID.4',
    'Arteon'
  ],
  'Tesla': ['Model 3', 'Model S', 'Model X', 'Model Y'],
  'BMW': ['3 Series', '5 Series', '7 Series', 'X1', 'X3', 'X5', 'i3', 'i8'],
  'Mercedes-Benz': [
    'C-Class',
    'E-Class',
    'S-Class',
    'GLA',
    'GLC',
    'GLE',
    'GLS',
    'A-Class'
  ],
  'Audi': ['A3', 'A4', 'A6', 'Q3', 'Q5', 'Q7', 'Q8', 'e-tron'],
  'Dodge': ['Charger', 'Challenger', 'Durango', 'Journey', 'Grand Caravan'],
  'Ram': ['1500', '2500', '3500', 'ProMaster City'],
  'Mazda': ['Mazda3', 'Mazda6', 'CX-3', 'CX-5', 'CX-9', 'MX-5 Miata'],
  'GMC': ['Sierra', 'Canyon', 'Terrain', 'Acadia', 'Yukon'],
  'Chrysler': ['300', 'Pacifica', 'Voyager'],
  'Buick': ['Encore', 'Enclave', 'Envision', 'Regal'],
  'Cadillac': ['CT4', 'CT5', 'XT4', 'XT5', 'Escalade'],
  'Acura': ['ILX', 'TLX', 'RDX', 'MDX', 'Integra'],
  'Infiniti': ['Q50', 'Q60', 'QX50', 'QX60', 'QX80'],
  'Lexus': ['IS', 'ES', 'RX', 'NX', 'GX', 'LS'],
  'Genesis': ['G70', 'G80', 'G90', 'GV70', 'GV80'],
  'Land Rover': [
    'Range Rover',
    'Range Rover Sport',
    'Discovery',
    'Defender',
    'Velar'
  ],
  'Volvo': ['S60', 'S90', 'XC40', 'XC60', 'XC90'],
};
